### ISSUE TITLE
匹配IP不完善

### ISSUE THREAD

**Issue by pphuahua** [chainreactors/gogo#17]
```
sudo ./gogo -i 172.16.0.0-253
[warn] System fd limit: 2560 , Please exec 'ulimit -n 65535' 
[warn] Now set threads to 2460 
[warn] Parse Ip Failed, skipped, Unable to resolve domain name:172.16.0.0-253. SKIPPED! 
[-] all targets format error
```
或者
```
sudo ./gogo -i 172.16.0.0-172.31.254.254                            
[warn] System fd limit: 2560 , Please exec 'ulimit -n 65535' 
[warn] Now set threads to 2460 
[warn] Parse Ip Failed, skipped, Unable to resolve domain name:172.16.0.0-172.31.254.254. SKIPPED! 
[-] all targets format error

```

提个小建议，可以直接用Fscan的那一套匹配IP的方法 ❤️

**Comment by M09Ic** [comment]
之前考虑过这个问题, 最后因为考虑到与其他工具联动时都不支持这种格式, 并且这种格式也会带来一些混淆, 例如`172.1.1-256.1` .

因为网段的划分都是规整的, 必须要通过子网掩码进行网段划分, 使用cidr的方式可能才是更贴近使用场景的解. 如果真的有类似需求, 还可以使用mapcidr生成对应的网段列表导入到gogo.

**Comment by pphuahua** [comment]
因为我是要扫172的这个内网网段，而B类地址如下
`B类：172.16.0.0-172.31.255.255 `
所以说我如果直接用`172.16.0.0/8`的话会连着公网的IP一起进行扫描

**Comment by M09Ic** [comment]
> 因为我是要扫172的这个内网网段，而B类地址如下 `B类：172.16.0.0-172.31.255.255 ` 所以说我如果直接用`172.16.0.0/8`的话会连着公网的IP一起进行扫描

只需要 `172.16.0.0/12` 即可

**Comment by M09Ic** [comment]
> 因为我是要扫172的这个内网网段，而B类地址如下 `B类：172.16.0.0-172.31.255.255 ` 所以说我如果直接用`172.16.0.0/8`的话会连着公网的IP一起进行扫描

对整个b段扫描会消耗大量时间,  我更建议使用 `-w 172` 进行启发式探测, workflow中已经配置了大部分常见的场景.
