### ISSUE TITLE
-F处理大文件结果有点吃力

### ISSUE THREAD

**Issue by okoling** [chainreactors/gogo#18]
7.0M    scan.txt_all_default_json.dat1

`gogo -F scan.txt_all_default_json.dat1 -o c` 处理起来挺久的
另外能不能 -F 处理导出 ip:port 这种类型 或者导出excel表格之类的

**Comment by M09Ic** [comment]
> `gogo -F scan.txt_all_default_json.dat1 -o c` 处理起来挺久的 

处理大文件确实比较缓慢, 后续将会作为优化的重点.

> 另外能不能 -F 处理导出 ip:port 这种类型 或者导出excel表格之类的

-F 可以导出很多类型的文件 , `gogo -F scan.txt_all_default_json.dat1 -o target`  就是ip:port文件. 如果要通过管道传给其他工具, 建议加上-q (不输出日志). 如果要输出到文件则为`gogo -F scan.txt_all_default_json.dat1 -o target -f target.txt` 

也支持导出到其他格式, -o 的值可以为 json(可再次作为-F的输入值), csv等. 或者是`-o ip,port,frame` 输出tab分割的多个值.

后续将会加急更新相关的文档.

**Comment by okoling** [comment]
可以边读边处理，大文件要等很久才能加载完 
内置的格式有哪些文档还没，等一波文档~

**Comment by M09Ic** [comment]
如果是format到标准格式的场景下, 因为需要合并同ip下的多个端口, 因此只能先读全部文件再进行格式化. 

之后默认格式考虑改为jsonlines格式, 这样非format的场景下, 可以边读边处理快速过滤出想要的结果.

**Comment by M09Ic** [comment]
当前支持的格式在这里. https://github.com/chainreactors/parsers/blob/master/gogo.go#L88

如果要过滤出http协议, 需要指定`--filter protocol::http` 

如果是需要url的话,需要指定  `-o url`

**Comment by okoling** [comment]
完美~
