### ISSUE TITLE
gogo -F里面的443端口cert证书里的域名怎么批量导出来呢

### ISSUE THREAD

**Issue by okoling** [chainreactors/gogo#19]
gogo -F里面的443端口cert证书里的域名怎么批量导出来呢

_Originally posted by @okoling in https://github.com/chainreactors/gogo/issues/18#issuecomment-1342748160_

**Comment by M09Ic** [comment]
cert的值会写入到result结构的host中， 可以使用`gogo -F 1.dat -o host` 导出。

感谢你的反馈， 之后将会在文档中补全说明
