### ISSUE TITLE
如图测试8083端口扫描，单一端口可扫描，使用top2扫描不出

### ISSUE THREAD

**Issue by sv3nbeast** [chainreactors/gogo#35]
<img width="1328" alt="image" src="https://github.com/chainreactors/gogo/assets/55974091/fa12ac54-6158-49b1-ae32-b249756bdcaa">

**Comment by wan-xiang** [comment]
--debug参数看一下或者抓包看看呢

**Comment by M09Ic** [comment]
这种情况大概率是timeout导致的， 在windows与linux上遇到该问题的概率较大， 和系统的并发调度与网络环境有关。

gogo在linux和mac上默认thread为4000， 在windows上为1000. 似乎4000并发对mac来说压力较大， 已经有多人反馈过mac上的这个问题。 后续考虑酱mac的默认thread也改为1000， 防止不可预期的网络丢包发生。

**Comment by M09Ic** [comment]
已于新版( https://github.com/chainreactors/gogo/releases/tag/v2.11.4 )注意到该问题, 并将mac上的默认并发数从4000 降到 1000.  如有特殊需求, 可以使用 `-t 4000` 指定需要的并发.

**Comment by sv3nbeast** [comment]
我重新去测试了，确实与mac所处的网络环境有极大关联，针对mac版调用不同的-t 线程，扫描结果会存在差异，需要手工找到较为优秀的线程，很多时候不是mac本身配置的压力大，是所处网络上的压力大

不知道这个寻找适合的线程，是否有思路进行自动定位一个区间，感觉会对扫描结果有很大帮助

**Comment by M09Ic** [comment]
https://github.com/epi052/feroxbuster 中有个auto-tune的参数实现了流控算法。 不管是gogo还是spray都挺需要的。 

我抽时间研究下， 实现一个类似auto-tune的流控算法应该会好一些。

如果在外网扫描放到vps上是更好的选择。
