### ISSUE TITLE
生成 sock.lock 文件疑问

### ISSUE THREAD

**Issue by s0k** [chainreactors/gogo#37]
在内网做B段扫描，扫一段时间自动产生 sock.lock 文件，然后就停止了，看了源码没看太懂，方便解答一下吗，谢谢。

**Comment by M09Ic** [comment]
.sock.lock一般是用在非交互式场景下观察扫描进度的， 默认会在扫描任务结束后自动删除。 

如果扫描了一段时间后任务停止， 且.sock.lock没有自动删除， 则说明被第三者kill了或者进程异常结束了。 

同时在扫描过程中， 真正的结果会保存在`.dat` 后缀的多个文件中， 一般写满4k的缓冲就会同步到文件一次。 就算任务没有扫描完成也可以使用 `gogo -F 1.dat` 格式化未完成的扫描任务。

**Comment by M09Ic** [comment]
另外 如果开启了 --debug， 则.sock.lock不会自动删除
