### ISSUE TITLE
mac端使用无法生成文件

### ISSUE THREAD

**Issue by zhaozebuchixiaobinggan** [chainreactors/gogo#39]
mac端使用gogo扫描完成后，强制输出文件或者自动以输出文件并无落地文件
![image](https://github.com/chainreactors/gogo/assets/61540220/0b1ddf87-c498-4df5-b3c1-1552ae87517c)
使用./gogo_darwin_amd64 -i 192.168.0.1/24 --af可落地文件但是使用./gogo_darwin_amd64 -i 192.168.0.1/24 -f 1.dat无法落地
![image](https://github.com/chainreactors/gogo/assets/61540220/090c1d52-888d-4f70-b4e0-04160649f360)
建议生成文件前缀别带.  mac端和linux端.命名的文件自动隐藏

**Comment by M09Ic** [comment]
本地测试 `gogo -f 1.dat -i 1.1.1.1` 可以正确生成文件. 如果无法生成文件， 可能是因为目标不存活。

 gogo的文件是懒生成的， 有了结果才会输出文件。
