### ISSUE TITLE
ip 输入功能

### ISSUE THREAD

**Issue by PoriaMs** [chainreactors/gogo#40]
希望能增加类似于 192.168.35.25-35 这样的输入功能

**Comment by M09Ic** [comment]
问题类似这个, https://github.com/chainreactors/gogo/issues/17

一直没有添加原因在issue17中提到过。

> 因为网段的划分都是规整的, 必须要通过子网掩码进行网段划分， 因此使用cidr实际上是更贴近场景的解决方案。
