### ISSUE TITLE
关于 body 的 md5匹配

### ISSUE THREAD

**Issue by PeiQi0** [chainreactors/gogo#44]
有些指纹得匹配body的md5, 在文件 v2/pkg/fingers/fingers.go 中匹配的是整个响应 content md5, 匹配body会好一点 
```
for _, md5s := range r.Regexps.MD5 {
	if md5s == parsers.Md5Hash([]byte(content)) {
		logs.Log.Debugf("%s finger hit, md5: %s", r.FingerName, md5s)
		return true, false, ""
	}
}
```
响应里返回的 date, server 字段随机性比较高没办法匹配 md5
<img width="1227" alt="image" src="https://github.com/chainreactors/gogo/assets/63465298/70213d73-4a5d-4559-a990-d54d4c5a56bc">

**Comment by M09Ic** [comment]
已确认问题, 下个版本中修改.
