### ISSUE TITLE
师傅zombie有消息吗

### ISSUE THREAD

**Issue by Layjb** [chainreactors/gogo#48]
师傅好，目前来看，爆破口令无法避免，当然有多种方式可以解决这个问题，但是实际情况下还是希望集成ssh等口令爆破，可以由参数控制。

**Comment by M09Ic** [comment]
zombie即将完成， 正在进行收尾工作，支持的协议与爆破方式是目前最多的工具，可以期待下

![image](https://github.com/chainreactors/gogo/assets/29176200/d63ed5e0-476f-444a-91d6-b70ec0598d78)

**Comment by M09Ic** [comment]
zombie 已设置为public, 欢迎体验，欢迎提供建议。 

https://github.com/chainreactors/zombie

**Comment by Layjb** [comment]
> zombie 已设置为public, 欢迎体验，欢迎提供建议。
> 
> https://github.com/chainreactors/zombie

对了师傅，gogo在使用过程中，问题最多的情况就是指纹匹配不到的问题，有很多指纹都是匹配不到的，同样使用ehole等等指纹识别可以匹配到，其中不乏很多oa指纹，这个问题师傅可以查证下。

**Comment by M09Ic** [comment]
gogo的指纹能力在某些情况下确实存在问题。 

1. 仅允许域名访问(需要配置host)的情况下。 因为gogo需要有限考虑内网使用，ip生成器与host的兼容很困难。 
2.  需要js跳转的情况下, gogo只支持30x跳转

如果有其他情况导致的指纹识别不准， 是否可以提供案例，可能是bug导致的。

可以体验下{spray](https://github.com/chainreactors/spray) 的指纹能力， 会比gogo强很多，特别是外网场景， 更推荐使用spray代替gogo。
