### ISSUE TITLE
白名单功能未生效

### ISSUE THREAD

**Issue by purpleteng** [chainreactors/gogo#49]
--exclude参数和--exclude-file参数没有生效，命令行添加了要排除的ip，但是在扫描的时候还是扫了
./gogo_linux_amd64 --ip=172.22.1.1/16 -w snoping --exclude=172.22.235.41/24 --af
<img width="614" alt="image" src="https://github.com/chainreactors/gogo/assets/48402957/0908d117-287a-4646-842b-f067c24b2534">

另外探测存活的时候子网掩码不规范，可以让显示输出的都默认为1/24这样的么，这样在白名单排除的时候可以方便弄
现在探测存活出来的网段都是172.22.216.41/24这样的，可能无法准确快速对应

**Comment by M09Ic** [comment]
1. 启发式扫描中因为目标为动态生成白名单不生效, 但在启发式探测完毕后进行完整扫描时会跳过白名单ip, 后续会考虑如何在启发式扫描中配置白名单. 
2. 子网掩码的会进行 `and` 位运算, 最后一位实际上会被忽略.  并且最后一位的数字实际上是发现C段存活ip, 某些时候用来debug使用.  也就是说 172.22.235.41/24 按照子网掩码的运算规则, 实际上等于 `172.22.235.0/24`
