### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by HiIk-9527** [chainreactors/gogo#65]
是否可以增加类似这种的指纹规则
该条为fofa语句body="lui_login_message_td" && body="form_bottom"
 我尝试在gogo中加入"lui_login_message_td"&&"form_bottom"生成时报错，或者是否有别的方法

**Comment by M09Ic** [comment]
gogo的指纹规则全都是 `or`的, 只需要找到一条能精准命中的指纹即可, 这也是鼓励使用者添加指纹的时候尽可能简洁. 

如果`lui_login_message_td`已经足够判断指纹, 那只需要填这个. 如果不能, 则建议换一个指纹, 因为`form_bottom` 也是一个很容易出现的字符串, 这并不是一个优雅的指纹. 

大部分时候, 我自己写的指纹会使用有特征的js/css/html路径.

**Comment by HiIk-9527** [comment]
好的感谢
