### ISSUE TITLE
通过文件传入和直接通过IP传入提供目标，结果不同

### ISSUE THREAD

**Issue by sv3nbeast** [chainreactors/gogo#72]
<img width="1619" alt="image" src="https://github.com/chainreactors/gogo/assets/55974091/bfe93e8c-6bbf-42f6-801c-b5fefbafe88f">

**Comment by M09Ic** [comment]
境外目标网络延迟较高导致的误报漏报暂时没办法解决. 要么找当地的扫描节点要么就提高timeout
