### ISSUE TITLE
主动指纹探测失效

### ISSUE THREAD

**Issue by HiIk-9527** [chainreactors/gogo#79]
使用的Releases 2.12.4版本 windwos amd64版本
![image](https://github.com/chainreactors/gogo/assets/69377487/50bb0df9-3f8d-41d0-a770-f3271c48efb0)

无法扫出
![image](https://github.com/chainreactors/gogo/assets/69377487/644b2c52-4edc-4603-9641-260dd5bf4216)

**Comment by M09Ic** [comment]
已在 https://github.com/chainreactors/gogo/releases/tag/v2.13.0 中修复
